					<div id="toc" class="four columns">
					
						<ul class="nav-bar">
							<li class="has-flyout"><a id ="ToC" class="inline cboxElement" href="#inline_content">Table of Contents</a>
								<div class="flyout medium">
									<dl class="nice vertical tabs">
									<dt>Spreadsheets</dt>
									<dd><a href="spreadsheets00.aspx">Introduction</a></dd>
									<dd><a href="spreadsheets00.1.aspx">Skills Mastery List</a></dd>
									<dd><a href="spreadsheets01.aspx">Basic Terms and Tools</a></dd>
									<dd><a href="spreadsheets02.aspx">Formatting Cells</a></dd>
									<dd><a href="spreadsheets03.aspx">Using Font and Text Effects</a></dd>
									<dd><a href="spreadsheets04.aspx">Alignment</a></dd>
									<dd><a href="spreadsheets05.aspx">Number Formatting</a></dd>
									<dd><a href="spreadsheets06.aspx">Shading and Borders</a></dd>
									<dd><a href="spreadsheets07.aspx">Sizing Columns and Rows</a></dd>
																		
<dd><a href="spreadsheets08.aspx">Margins</a></dd>
									
<dd><a href="spreadsheets09.aspx">Headers and Footers</a></dd>
									
<dd><a href="spreadsheets10.aspx">Page Orientation</a></dd>
									
<dd><a href="spreadsheets11.aspx">Formulas and Functions</a></dd>
									
						
<dd><a href="spreadsheets12.aspx">AutoSum (&#8721;) Function</a></dd>
									
<dd><a href="spreadsheets13.aspx">Date and/or Time Function</a></dd>
														
<dd><a href="spreadsheets14.aspx">Copying Functions and Formulas</a></dd>
									
<dd><a href="spreadsheets15.aspx">Charts</a></dd>
									
<dd><a href="spreadsheets16.aspx">Data Ranges in Charts</a></dd>
									
<dd><a href="spreadsheets17.aspx">Chart Options</a></dd>
														
<dd><a href="spreadsheets18.aspx">Viewing Options</a></dd>
									
<dd><a href="spreadsheets19.aspx">Print Options</a></dd>
									
<dd><a href="spreadsheets20.aspx">Key Terms</a></dd>


<dd><a href="spreadsheets-videos.aspx">Videos</a></dd>
									</dl>
								</div>
							</li>
						</ul>
					</div>
				</div>