					<div id="toc" class="four columns">
					
						<ul class="nav-bar">
							<li class="has-flyout"><a id ="ToC" class="inline cboxElement" href="#inline_content">Table of Contents</a>
								<div class="flyout medium">
									<dl class="nice vertical tabs">
									  <dt>Word Processing</dt>
									  <dd><a href="wordprocessing00.aspx">Introduction</a></dd>
									  <dd><a href="wordprocessing00.1.aspx">Skills Mastery List</a></dd>
									  <dd><a href="wordprocessing01.aspx">Orientation to Office</a></dd>
									  <dd><a href="wordprocessing02.aspx">What Is Word Processing?</a></dd>
									  <dd><a href="wordprocessing03.aspx">The Document Cycle</a></dd>
									  <dd><a href="wordprocessing04.aspx">Basic Tools And Terms</a></dd>
									  <dd><a href="wordprocessing05.aspx">Word Processing Formats</a></dd>
									  <dd><a href="wordprocessing06.aspx">Setting Page Margins And Page Orientation</a></dd>
									  <dd><a href="wordprocessing07.aspx">Justification And Alignment Of Text </a></dd>
									  <dd><a href="wordprocessing08.aspx">Applying Fonts and Text Effects</a></dd>
									  <dd><a href="wordprocessing09.aspx">Spacing in Documents</a></dd>
									  <dd><a href="wordprocessing10.aspx">Headers And Footers</a></dd>
									  <dd><a href="wordprocessing11.aspx">Date and/or Time Field</a></dd>
									  <dd><a href="wordprocessing12.aspx">Borders and Shading For Text And Paragraph</a></dd>
									  <dd><a href="wordprocessing13.aspx">Page Border And Border Art </a></dd>
									  <dd><a href="wordprocessing14.aspx">Tables</a></dd>
									  <dd><a href="wordprocessing15.aspx">Copy, Cut and Paste</a></dd>
									  <dd><a href="wordprocessing16.aspx">Find And Replace</a></dd>
									  <dd><a href="wordprocessing17.aspx">Key Terms</a></dd>

<dd><a href="wordprocessing-videos.aspx">Videos</a></dd>
									</dl>
								</div>
							</li>
						</ul>
					</div>
				</div>