					<div id="toc" class="four columns">
					
						<ul class="nav-bar">
							<li class="has-flyout"><a id ="ToC" class="inline cboxElement" href="#inline_content">Table of Contents</a>
								<div class="flyout medium">
									<dl class="nice vertical tabs">
									  <dt>Computer Basics</dt>
									  
<dd><a href="computerbasics00.aspx">Introduction</a></dd>
									  
<dd><a href="computerbasics01.aspx">Basic Computer Hardware</a></dd>
									  
<dd><a href="computerbasics02.aspx">Desktop, Mouse and Booting Up</a></dd>
									  
<dd><a href="computerbasics03.aspx">Windows &amp; Microsoft Office Versions</a></dd>
									  
<dd><a href="computerbasics04.aspx">Windows on Your Desktop</a></dd>
									  
<dd><a href="computerbasics05.aspx">Start Button</a></dd>
									  
<dd><a href="computerbasics06.aspx">Keyboard</a></dd>
									  
<dd><a href="computerbasics07.aspx">Computer Software and Hardware</a></dd>
									  
<dd><a href="computerbasics08.aspx">Computer Memory</a></dd>
									  
<dd><a href="computerbasics09.aspx">Data Storage on the Computer</a></dd>
									  
<dd><a href="computerbasics10.aspx">Default Storage Location for Data</a></dd>
									  
<dd><a href="computerbasics11.aspx">Key Terms</a></dd>

<dd><a href="computerbasics-videos.aspx">Videos</a></dd>
									</dl>
								</div>
							</li>
						</ul>
					</div>
				</div>