<div id="empHeader">
	<div class="row">
		<div class="twelve columns">
			<h2 class="two columns"><span>Empowerment Concepts</span></h2>
			<nav class="ten columns">
				<ul class="nav-bar">
					
					
<li><a href="Login.aspx"><i class="icon-signout icon-large"></i> Logout</a></li>
					

<li><a href="certification.aspx"><i class="icon-pencil icon-large"></i> Certification Exams</a></li>
					

					

<li><a href="GradeBook.aspx"><i class="icon-book icon-large"></i> Gradebook</a></li>


<li><a href="setup.aspx"><i class="icon-cog icon-large"></i> Set Up</a></li>

				</ul>
			</nav>
		</div>
	</div>
</div>



