
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->

	<head runat="server">
		<meta charset="utf-8" />
	
		<title>DIDL Jumpstart | Empowerment Concepts</title>

		<meta name="description" content="http://didljumpstart.empconcepts.com">
		<meta name="author" content="Andrew - SkyyMedia">

  	<!-- iPhone, iPad and Android specific settings -->	
  		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1;">
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		
	<!-- For Modern Browsers -->
		<link rel="shortcut icon" href="img/favicons/favicon.png">
		<!-- For everything else -->
		<link rel="shortcut icon" href="img/favicons/favicon.ico">
		<!-- For retina screens -->
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/favicons/apple-touch-icon-retina.png">
		<!-- For iPad 1-->
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/favicons/apple-touch-icon-ipad.png">
		<!-- For iPhone 3G, iPod Touch and Android -->
		<link rel="apple-touch-icon-precomposed" href="img/favicons/apple-touch-icon.png">
		
	<!-- Styles -->

		
<link rel="stylesheet" type="text/css" href="css/base.css">
	<link rel="stylesheet" type="text/css" href="css/app.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome.css">
		<link rel="stylesheet" type="text/css" href="css/colorbox.css">
		
<link rel="stylesheet" type="text/css" href="css/quiz-styles.css">
		<link rel="stylesheet" type="text/css" href="css/fonts.css">
		
<link rel="stylesheet" type="text/css" href="css/elfinder.css">
		
<link rel="stylesheet" type="text/css" href="css/sublimevideo_lightbox.css">
		<link rel="stylesheet" type="text/css" href="css/playlist.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/buttonbar.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/reveal.css" media="screen" />

		
<link href="css/slider.css" rel="stylesheet" type="text/css" />
		
		
<linkrel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css" id="theme">



<link rel="stylesheet" type="text/css" href="css/video-js.css">
	
	

<!--[if lt IE 9]>
		
<link rel="stylesheet" type="text/css" href="styles/ie.css">
		
<![endif]-->
	
	<!-- IE Fix for HTML5 Tags -->
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<!--[if gte IE 9]>
  			<style type="text/css">
    		.gradient {
       		filter: none;
   			 }
  			</style>
			<![endif]-->

	<!-- Scripts -->
	
		<!-- Load JQuery -->		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

		<!-- Load JQuery UI -->
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js" type="text/javascript"></script>
		
		<script src="" href="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" type="text/javascript"></script>
		
		<script src="js/modernizr.foundation.js"></script>
		<script src="js/jquery.colorbox-min.js"></script>
		<script src="js/foundation.js"></script>
		<script src="js/app.js"></script>
		
		<!-- Load Sublime Player -->




	
                <script type="text/javascript" src="js/sublimevideo.js"></script>
        				
		<!-- Load JQuery Slider Nav -->
		<script src="js/slidernav.js"></script>
		
		<!-- Load JQuery Quiz Questions -->
		<script src="js/jquery.jquizzy.js"></script>
		<script src="js/jquery.jquizzy-min.js"></script>
		
		<!-- Load ToolTips-->	


		
		<!-- Load JQuery Jquizzy -->
		<script src="js/cb-practice-q.js"></script>
		<script src="js/s-practice-q.js"></script>
		<script src="js/i-practice-q.js"></script>
		<script src="js/ff-practice-q.js"></script>
		<script src="js/wp-practice-q.js"></script>	
		
		<!-- Load JQuery File Manager -->
		<script type="text/javascript" src="js/elfinder.min.js"></script>
		<script type="text/javascript" src="js/custom.js"></script>
		
		<!-- Load JQuery Slide Show -->	
	    <script type="text/javascript" src="js/jquery.cycle.all.js"></script>
        <script type="text/javascript" src="js/script.js"></script>
        
		<!-- Load TypeKit-->	
		<script type="text/javascript" src="http://use.typekit.com/zaa8rni.js"></script>
		<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
		


		
	








</head>
