
<div class="three columns small">			
				<h4 id="user"><span>User Name</span></h4>

			    <aside id="sidebar">
			    	
			    	<!-- Begin of Navigation -->
			    	<nav id="nav">
				    	<ul class="menu collapsible shadow-bottom">
				    		<li>
				    		<a class="dashboard" href="../../dashboard.aspx"><span>Dashboard</span></a></li>
				    		
				    	</ul>
			    	</nav> <!--! end of #nav -->
			    </aside>
			</div>