			<div class="three columns small">			
				<h4 id="user"><span>User Name</span></h4>

			    <aside id="sidebar">
			    	
			    	<!-- Begin of Navigation -->
			    	<nav id="nav">
				    	<ul class="menu collapsible shadow-bottom">
				    		<li>
				    		


<a class="dashboard" href="dashboard.aspx"><span>Dashboard</span></a></li>
				    		<li class="sideNav-comp">
				    			<a class="basics" href="javascript:void(0);"><span>Computer Basics</span></a>
				    			<ul class="sub">
				    				<li><a href="computerbasics00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="computerbasics-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="computerbasics-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				<li>


<a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		</li>
				    		<li class="sideNav-file">
				    			<a class="filemanagement" href="filemanagement00.aspx"><span>Files & Folders</span></a>
				    			<ul class="sub">
				    				<li><a href="filemanagement00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="filemanagement-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="filemanagement-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				

<li><a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		</li>
				    		<li class="sideNav-internet">
				    			<a class="internets" href="internet00.aspx"><span>Internet</span></a>
				    			<ul class="sub">
				    				<li><a href="internet00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="internet-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="internet-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				<li><a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		</li>				    
				    		<li class="sideNav-word">
				    			<a class="word" href="wordprocessing00.aspx"><span>Word Processing</span></a>
				    			<ul class="sub">
				    				<li><a href="wordprocessing00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="wordprocessing-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="wordprocessing-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				<li><a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		</li>
				    		


<li class="sideNav-spread">
				    			<a class="spreadsheets" href="spreadsheets00.aspx"><span>Spreadsheets</span></a>
				    			<ul class="sub">
				    				<li><a href="spreadsheets00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="spreadsheets-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="spreadsheets-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				<li><a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		




<li class="sideNav-finalexam">
				    			<a class="finalexam" href="certify00.aspx"><span>Final Exam</span></a>
				    			<ul class="sub">
				    				<li><a href="finalexam00.aspx">&#x25B8;&nbsp; Study</a></li>
				    				<li><a href="finalexam-practice.aspx">&#x25B8;&nbsp; Practice</a></li>
				    				<li><a href="finalexam-connections.aspx">&#x25B8;&nbsp; Review</a></li>
				    				<li><a href="certification.aspx">&#x25B8;&nbsp; Certify</a></li>
				    			</ul>
				    		</li>
				    		





<li><a class="keyterms" href="keyterms.aspx" ><span>Key Terms</span></a></li>
				    	</ul>
			    	</nav> <!--! end of #nav -->
			    </aside>
			</div>
