			<div class="three columns small">			
				<h4 id="user"><span>User Name</span></h4>

			    <aside id="sidebar">
			    	
			    	<!-- Begin of Navigation -->
			    	<nav id="nav">
				    	<ul class="menu collapsible shadow-bottom">
				    		<li>
				    		


<a class="dashboard" href="grader.aspx"><span>Dashboard</span></a></li>
				    						    							    						    		<li class="sideNav-file">
				    			<a class="filemanagement" href="/checklists/didlFF_checklist.docx"><span>Files & Folders</span></a>
				    							    		</li>
				    		
				    					    
				    		<li class="sideNav-word">
				    			<a class="word" href="/checklists/didlWP_checklist.docx"><span>Word Processing</span></a>
				    					    		</li>
				    		


<li class="sideNav-spread">
				    			<a class="spreadsheets" href="/checklists/didlSS_checklist.docx"><span>Spreadsheets</span></a>
				    						    		




	    	</nav> <!--! end of #nav -->
			    </aside>
			</div>
