	<div style="display:none;">
		<div id="inline_content" class="row">
			<div class="twelve columns">
			    <div class="modalContent">
			     	<h4>Files &amp; Folders</h4>
			     	<a class="closebutton" href="#"><span>Go Back</span> &#215;</a>
					<hr>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement00.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a class="ToCLink" href="filemanagement00.aspx">Introduction</a>
						</div>
					</div>	
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement00.1.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement00.1.aspx">Skills Mastery List</a>
						</div>
					</div>	
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement01.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a  href="filemanagement01.aspx">The C: Drive Quick Review</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement02.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement02.aspx">Creating a Folder</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement03.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement03.aspx">Moving and Copying Files and Folders</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement04.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement04.aspx">Deleting a File or Folder</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement05.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement05.aspx">Renaming a File or Folder</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement06.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement06.aspx">Selecting Multiple Files or Folders</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement07.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement07.aspx">Viewing Options</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement08.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement08.aspx">Full Path Name for a File </a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement09.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement09.aspx">Searching for Files or Folders</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement10.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement10.aspx">Available Storage Space</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement11.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement11.aspx">Using Windows Help</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement12.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement12.aspx">Print Screen</a>
						</div>
					</div>
					



<div class="ToCmenuItem">
						<a class="ToCimage" href="filemanagement13.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filemanagement13.aspx">Key Terms</a>
						</div>
					</div>

<div class="ToCmenuItem">
						<a class="ToCimage" href="filesandfolders-videos.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="filesandfolders-videos.aspx">Videos</a>
						</div>
					</div>







				
				</div>
			</div>
	    </div>
	</div>
