	<div style="display:none;">
		<div id="inline_content" class="row">
			<div class="twelve columns">
			    <div class="modalContent">
			     	<h4>Spreadsheets</h4>
			     	<a class="closebutton" href="#"><span>Go Back</span> &#215;</a>
					<hr>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets00.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets00.aspx">Introduction</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets00.1.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets00.1.aspx">Skills Mastery List</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets01.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets01.aspx">Basic Terms and Tools</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets02.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets02.aspx">Formatting Cells</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets03.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets03.aspx">Using Font and Text Effects</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets04.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets04.aspx">Alignment</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets05.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets05.aspx">Number Formatting</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets06.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets06.aspx">Shading and Borders</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets07.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets07.aspx">Sizing Columns and Rows</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets08.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets08.aspx">Margins</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets09.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets09.aspx">Headers and Footers</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets10.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets10.aspx">Page Orientation</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets11.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets11.aspx">Formulas and Functions</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets12.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets12.aspx">AutoSum (&#8721;) Function</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets13.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets13.aspx">Date and/or Time Function</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets14.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets14.aspx">Copying Functions and Formulas</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets15.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets15.aspx">Charts</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets16.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets16.aspx">Data Ranges in Charts</a>
						</div>
					</div>					
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets17.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets17.aspx">Chart Options</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets18.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets18.aspx">Viewing Options</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets19.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets19.aspx">Print Options</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets20.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets20.aspx">Key Terms</a>
						</div>
					</div>
					

<div class="ToCmenuItem">
						<a class="ToCimage" href="spreadsheets-videos.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="spreadsheets-videos.aspx">Videos</a>
						</div>
					</div>
					


		




</div>
	    </div>
	</div>
