	<div style="display:none;">
		<div id="inline_content" class="row">
			<div class="twelve columns">
			    <div class="modalContent">
			     	<h4>Computer Basics</h4>
			     	<a class="closebutton" href="#"><span>Go Back</span> &#215;</a>
					<hr>
					
<div class="ToCmenuItem">
						

<a class="ToCimage" href="computerbasics00.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a class="ToCLink" href="computerbasics00.aspx">Introduction</a>
						</div>
					</div>
					
<div class="ToCmenuItem">
						

<a class="ToCimage" href="computerbasics01.aspx">&nbsp;</a>
						
		<div class="ToCLink">
							<a class="ToCLink" href="computerbasics01.aspx">Basic Computer Hardware</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics02.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics02.aspx">Desktop, Mouse and Booting Up</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics03.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics03.aspx">Windows &amp; Microsoft Office Versions</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics04.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics04.aspx">Windows On Your Desktop</a>
						</div>
					</div>					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics05.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics05.aspx">Start Button</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics06.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics06.aspx">Keyboard</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics07.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics07.aspx">Computer Software and Hardware</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics08.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics08.aspx">Computer Memory</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics09.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics09.aspx">Data Storage on the Computer</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics10.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics10.aspx">Default Storage Location for Data</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics11.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics11.aspx">Key Terms</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="computerbasics-videos.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="computerbasics-videos.aspx">Videos</a>
						</div>
					</div>					
				</div>
			</div>
	    </div>
	</div>
