				<div id="toc" class="four columns">
					
						<ul class="nav-bar">
							<li class="has-flyout"><a id ="ToC" class="inline cboxElement" href="#inline_content">Table of Contents</a>
								<div class="flyout medium">
									<dl class="nice vertical tabs">
									  <dt>Files &amp; Folders</dt>
									  <dd><a href="filemanagement00.aspx">Introduction</a></dd>
									  
<dd><a href="filemanagement00.1.aspx">Skills Mastery List</a></dd>
									  
<dd><a href="filemanagement01.aspx">The C: Drive Quick Review</a></dd>
									  
<dd><a href="filemanagement02.aspx">Creating a Folder</a></dd>
									 
<dd><a href="filemanagement03.aspx">Moving And Copying Files and Folders</a></dd>
									  
<dd><a href="filemanagement04.aspx">Deleting a File Or Folder</a></dd>
									  
<dd><a href="filemanagement05.aspx">Renaming a File Or Folder</a></dd>
									  
<dd><a href="filemanagement06.aspx">Selecting Multiple Files Or Folders</a></dd>
									 
<dd><a href="filemanagement07.aspx">Viewing Options</a></dd>
									  
<dd><a href="filemanagement08.aspx">Full Path Name for A File </a></dd>
									  
<dd><a href="filemanagement09.aspx">Searching for Files Or Folders</a></dd>
									  
<dd><a href="filemanagement10.aspx">Available Storage Space</a></dd>
									  
<dd><a href="filemanagement11.aspx">Using Windows Help</a></dd>
									  
<dd><a href="filemanagement12.aspx">Print Screen</a></dd>
									  
<dd><a href="filemanagement13.aspx">Key Terms</a></dd>

	
<dd><a href="filesandfolders-videos.aspx">Videos</a></dd>
								</dl>
								</div>
							</li>
						</ul>
					</div>
				</div>