	<div style="display:none;">
		<div id="inline_content" class="row">
			<div class="twelve columns">
			    <div class="modalContent">
			     	<h4>Word Processing</h4>
			     	<a class="closebutton" href="#"><span>Go Back</span> &#215;</a>
					<hr>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing00.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a  class="ToCLink" href="wordprocessing00.aspx">Introduction</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing00.1.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing00.1.aspx">Skills Mastery List</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing01.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing01.aspx">Orientation To Office</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing02.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing02.aspx">What Is Word Processing?</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing03.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing03.aspx">The Document Cycle</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing04.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing04.aspx">Basic Tools And Terms</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing05.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing05.aspx">Word Processing Formats</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing06.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing06.aspx">Setting Page Margins And Page Orientation</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing07.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing07.aspx">Justification And Alignment of Text</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing08.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing08.aspx">Applying Fonts and Text Effects</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing09.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing09.aspx">Spacing in Documents</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing10.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing10.aspx">Headers And Footers</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing11.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing11.aspx">Date And/Or Time Field</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing12.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing12.aspx">Borders And Shading For Text And Paragraph</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing13.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing13.aspx">Page Border And Border Art </a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing14.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing14.aspx">Tables</a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing15.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing15.aspx">Copy, Cut, And Paste </a>
						</div>
					</div>
					<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing16.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing16.aspx">Find And Replace</a>
						</div>
					</div>
					



<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing17.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing17.aspx">Key Terms</a>
						</div>					
					</div>

<div class="ToCmenuItem">
						<a class="ToCimage" href="wordprocessing-videos.aspx">&nbsp;</a>
						<div class="ToCLink">
							<a href="wordprocessing-videos.aspx">Videos</a>
						</div>					
					</div>









				
				</div>
			</div>
	    </div>
	</div>
