					<div id="toc" class="four columns">
					
						<ul class="nav-bar">
							<li class="has-flyout"><a id ="ToC" class="inline cboxElement" href="#inline_content">Table of Contents</a>
								<div class="flyout medium">
									<dl class="nice vertical tabs">
									  <dt>Internet</dt>
									  <dd><a href="internet00.aspx">Introduction</a></dd>
									  <dd><a href="internet00.1.aspx">Skills Mastery List</a></dd>
									  <dd><a href="internet01.aspx">The Internet</a></dd>
									  <dd><a href="internet02.aspx">Viewing Text And Documents On The Web</a></dd>
									  <dd><a href="internet03.aspx">Internet And Web Addresses </a></dd>
									  <dd><a href="internet04.aspx">Email Through The Internet</a></dd>
									  <dd><a href="internet05.aspx">Internet Security</a></dd>
									  <dd><a href="internet06.aspx">Internet Privacy</a></dd>
									  <dd><a href="internet07.aspx">Searching On The Internet</a></dd>
									  <dd><a href="internet08.aspx">Evaluate Information On The Internet</a></dd>
									  <dd><a href="internet09.aspx">Key Terms</a></dd>



<dd><a href="internet-videos.aspx">Videos</a></dd>
									</dl>							
								</div>
							</li>
						</ul>
					</div>
				</div>