<div id="empHeader">
	<div class="row">
		<div class="twelve columns">
			<h2 class="two columns"><span>Empowerment Concepts</span></h2>
			<nav class="ten columns">
                <div Style="float:right">
                    <asp:HyperLink ID="HyperLink1" runat="server" ImageUrl="~/images/icons/CloseIt.jpg" NavigateUrl="~/dashboard.aspx">HyperLink</asp:HyperLink>
                </div>
			</nav>
		</div>
	</div>
</div>

