<div id="empHeader">
	<div class="row">
		<div class="twelve columns">
			<h2 class="two columns"><span>Empowerment Concepts</span></h2>
			<nav class="ten columns">
				<ul class="nav-bar">
					
					
<li><a href="Login.aspx"> Login</a></li>

					

					

					

<li><a href="features.aspx"> Features</a></li>


<li><a href="index.aspx">Home</a></li>

				</ul>
			</nav>
		</div>
	</div>
</div>



