<div id="empHeader">
	<div class="row">
		<div class="twelve columns">
			<h2 class="two columns"><span>Empowerment Concepts</span></h2>
			<nav class="ten columns">
				            <div id="nddbtn1">
                <a href="#" class="nddbutton">
                    <span class="txt">Settings</span>
                    <span class="ar">&#9660;</span>
                </a>
                <div class="nddmenu">
                    <ul>
                        <li><a href="#">Edit Profile</a></li>
                        <li><a href="#">Account Settings</a></li>
                        <li><a href="#">Appear Offline</a></li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>
			</nav>
		</div>
	</div>
</div>



