<div id="empHeader">
	<div class="row">
		<div class="twelve columns">
			<h2 class="two columns"><span>Empowerment Concepts</span></h2>
			<nav class="ten columns">
				<ul class="nav-bar">
							
<li><a href="Login.aspx"><i class="icon-signout icon-large"></i> Logout</a></li>

<li><a href="graderkeys.aspx"><i class="icon-book icon-large"></i> Keys</a></li>


										

					

<li><a href="gradergradebook.aspx"><i class="icon-book icon-large"></i> Gradebook</a></li>




<li><a href="grader1.aspx"><i class="icon-book icon-large"></i> Task Grading</a></li>




				</ul>
			</nav>
		</div>
	</div>
</div>



